[package]
name = "toylisp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-new = "0.5.9"
enum-as-inner = "0.5.0"
enum-display-derive = "0.1.1"
